var nl = ee.ImageCollection('NOAA/VIIRS/DNB/MONTHLY_V1/VCMSLCFG').median().select('avg_rad')
// nl = ee.Image('users/saurabhk1396/myExportImageTask2')
// nl = ee.Image('users/saurabhk1396/fr')
// print(nl)
var fc = ee.FeatureCollection('ft:1XULuZoTOzBNiIguwxpKddIqt04SJGzSoeAdGucg','kml_4326')
fc = fc.filter(ee.Filter.eq('name_sort','India'))
nl = nl.expression('a/20', {'a': nl.select('avg_rad')})
nl = nl.clip(fc)
Export.image.toDrive(nl)
var h = ee.FeatureCollection('ft:160wc9WElpq9daaoAceg6jfTXvf5l_6D_oKS_UlXj','geometry')
// var orissa1 = ee.FeatureCollection('ft:14l1RMzq8K2X96uRlslLAIbY5A8vgw_R_f-LhV0j_','geometry')
print(h.size())
h = h.filter(ee.Filter.lt("SOL",2000))
// h = h.filterBounds(orissa1)
Map.addLayer(nl)
h = h.filter(ee.Filter.gt("SOL",60))
// print(orissa1.size())
// orissa1 = orissa1.filter(ee.Filter.gt('village_code_2011',0))
// print(orissa1.size())
Map.addLayer(h)

